@startmindmap
* NewYearResolution
** UI
*** maquette
*** responsiv
** ecranAccueil
*** ecranConnection
**** ecranResolutions
**** ecranAjouterResolutions
*** topResolutions
left side
** setUpProjet
*** creationBDD
**** ScrumUser
***** creationFakeUser
**** gestionResolution
***** CRUDResolutionUser
@endmindmap