name: Maven Build & Sonar analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name : build develope branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Maven Build & Sonar analysis
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        #run: mvn -B verify --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: docker build -t new-year-resolution .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: univ-smb-m1-isc-2021/newyearsresolution_belhoauzia_carrera/main
          tags: latest
